import { expect, test, type APIRequestContext, type Page } from '@playwright/test'
import { apiSend, registerFundedCustomer } from './helpers'

function accountIdFrom(page: Page): number {
  return Number(new URL(page.url()).pathname.split('/').pop())
}

async function withdraw(request: APIRequestContext, accountId: number, amount: string, description: string) {
  const response = await apiSend(request, 'post', '/api/customer/withdrawals', { accountId, amount, description }, {
    'Idempotency-Key': crypto.randomUUID(),
  })
  expect(response.status(), `withdraw ${amount}`).toBe(200)
}

async function transfer(request: APIRequestContext, sourceAccountId: number, destinationAccountNumber: string, amount: string, description: string) {
  const response = await apiSend(request, 'post', '/api/customer/transfers', { sourceAccountId, destinationAccountNumber, amount, description }, {
    'Idempotency-Key': crypto.randomUUID(),
  })
  expect(response.status(), `transfer ${amount}`).toBe(200)
}

test.describe('Insights and unusual activity (packaged app)', () => {
  test('a brand-new customer sees "Insufficient history" and no invented numbers', async ({ page }) => {
    await registerFundedCustomer(page, 'Cold Start', '1000')
    await page.goto('/insights')

    const projection = page.getByRole('region', { name: /Projected month-end spending/i })
    await expect(projection.getByText('Insufficient history')).toBeVisible()
    await expect(projection.getByText(/₹/)).toHaveCount(0)
    await expect(page.getByText('Nothing unusual noticed.')).toBeVisible()
    await expect(page.getByRole('region', { name: /This month so far/i }).getByText('Observed')).toBeVisible()
    await expect(page.getByText(/not generated by AI/i)).toBeVisible()
    await expect(page.locator('body')).not.toContainText(/\d+\s*%\s*confidence/i)
  })

  test('an unusually large payment reaches only its owner live over SSE, and nothing is blocked', async ({ browser }) => {
    const contextA = await browser.newContext()
    const contextB = await browser.newContext()
    const pageA = await contextA.newPage()
    const pageB = await contextB.newPage()

    await registerFundedCustomer(pageA, 'Alice Unusual', '50000')
    const aAccountId = accountIdFrom(pageA)
    await registerFundedCustomer(pageB, 'Bob Bystander', '50000')

    // Alice builds a normal pattern: six payments of about 1,500.
    for (const amount of ['1500.00', '1510.00', '1520.00', '1530.00', '1540.00', '1550.00']) {
      await withdraw(pageA.request, aAccountId, amount, 'Groceries')
    }

    // Both watch their Insights page; from here on nobody refreshes.
    await pageA.goto('/insights')
    await pageB.goto('/insights')
    await expect(pageA.getByText('Nothing unusual noticed.')).toBeVisible()
    await expect(pageB.getByText('Nothing unusual noticed.')).toBeVisible()

    await withdraw(pageA.request, aAccountId, '20000.00', 'Large one-off purchase')

    // Delivered live to Alice, with an understandable explanation and honest labelling.
    const alert = pageA.getByRole('region', { name: /Unusual activity/i })
    await expect(alert.getByText(/Unusual activity · Unusually large payment \(statistical check\)/)).toBeVisible({ timeout: 15_000 })
    await expect(alert.getByText(/typical payment \(median\)/)).toBeVisible()
    await expect(alert.getByText(/not a finding of fraud/)).toBeVisible()
    await expect(alert.getByText(/nothing was blocked/i).first()).toBeVisible()
    await expect(pageA.locator('main')).not.toContainText(/fraud alert|confirmed fraud/i)

    // Bob never sees it, live or by API.
    await pageB.waitForTimeout(2000)
    await expect(pageB.getByText('Nothing unusual noticed.')).toBeVisible()
    const bAlerts = await pageB.request.get('/api/customer/insights/alerts')
    expect(await bAlerts.json()).toEqual([])
    const bNotifications = await pageB.request.get('/api/notifications')
    expect(JSON.stringify(await bNotifications.json())).not.toContain('UNUSUAL_ACTIVITY')

    // The alert is only informational: the payment went through and the account stays fully usable.
    const account = await (await pageA.request.get(`/api/customer/accounts/${aAccountId}`)).json()
    expect(account.status).toBe('ACTIVE')
    expect(Number(account.balance)).toBeCloseTo(50000 - 9150 - 20000, 2)
    await withdraw(pageA.request, aAccountId, '100.00', 'Still works')

    await contextA.close()
    await contextB.close()
  })

  test('repeated identical payments raise exactly one alert, however many repeats follow', async ({ browser }) => {
    const contextA = await browser.newContext()
    const contextB = await browser.newContext()
    const pageA = await contextA.newPage()
    const pageB = await contextB.newPage()

    await registerFundedCustomer(pageA, 'Alice Repeats', '20000')
    const aAccountId = accountIdFrom(pageA)
    const b = await registerFundedCustomer(pageB, 'Bob Recipient', '100')

    await pageA.goto('/insights')
    for (let i = 0; i < 5; i++) {
      await transfer(pageA.request, aAccountId, b.accountNumber, '300.00', 'Rent share')
    }

    await expect(pageA.getByText(/Unusual activity · Repeated payments \(rule\)/)).toBeVisible({ timeout: 15_000 })
    const alerts = await (await pageA.request.get('/api/customer/insights/alerts')).json()
    expect(alerts.filter((a: { ruleCode: string }) => a.ruleCode === 'REPEATED_PAYMENT')).toHaveLength(1)
    await expect(pageA.getByText(/Unusual activity · Repeated payments/)).toHaveCount(1)

    expect(await (await pageB.request.get('/api/customer/insights/alerts')).json()).toEqual([])

    await contextA.close()
    await contextB.close()
  })
})
