import { useInsights, useUnusualActivity } from '../../api/useInsights'
import { ErrorBanner, EmptyState, LoadingState } from '../../components/States'
import { formatDateTime, formatInr, formatIsoDate, formatMonth } from '../../lib/format'
import type { BudgetEstimateStatus, GoalProjectionStatus, InsightsBudgetEstimate, InsightsGoal } from '../../api/types'

const BUDGET_STATUS: Record<BudgetEstimateStatus, { label: string; className: string }> = {
  ALREADY_OVER: { label: 'Already over', className: 'badge-danger' },
  PROJECTED_OVER: { label: 'Projected to exceed', className: 'badge-warning' },
  POSSIBLY_OVER: { label: 'Could exceed (upper estimate)', className: 'badge-warning' },
  ON_TRACK: { label: 'On track', className: 'badge-active' },
  INSUFFICIENT_HISTORY: { label: 'Insufficient history', className: 'badge-closed' },
}

const GOAL_STATUS: Record<GoalProjectionStatus, string> = {
  OK: 'Estimate',
  COMPLETED: 'Target reached',
  INSUFFICIENT_HISTORY: 'Insufficient history',
  NO_POSITIVE_TREND: 'No positive contribution trend',
}

export function InsightsPage() {
  const insights = useInsights()
  const unusual = useUnusualActivity()

  if (insights.isLoading) return <LoadingState label="Calculating your insights…" />
  if (insights.isError) return <ErrorBanner error={insights.error} onRetry={() => insights.refetch()} />
  const data = insights.data
  if (!data) return null

  const { observed, projection } = data

  return (
    <div className="stack">
      <div>
        <h1>Insights</h1>
        <p className="text-muted">
          Everything on this page is calculated from your own transactions using standard statistics. It is not generated by AI.
          Observed figures are what already happened; projections are estimates and are always labelled.
        </p>
      </div>

      <section className="card" aria-labelledby="unusual-heading">
        <h2 id="unusual-heading">Unusual activity</h2>
        <p className="text-muted">
          Statistical checks and simple rules on your own payments. These are prompts to take a look — they are not fraud
          detection, and nothing is ever blocked or frozen automatically.
        </p>
        {unusual.isError && <ErrorBanner error={unusual.error} onRetry={() => unusual.refetch()} />}
        {unusual.data && unusual.data.length === 0 && <EmptyState>Nothing unusual noticed.</EmptyState>}
        <div className="stack">
          {unusual.data?.map((a) => (
            <div key={a.id} className="alert alert-warning" style={{ margin: 0 }}>
              <div className="row-between" style={{ marginBottom: 6 }}>
                <span className="badge badge-warning">Unusual activity · {a.label}</span>
                <span className="text-muted">{formatDateTime(a.createdAt)}</span>
              </div>
              <div>{a.explanation}</div>
              {a.transactionReference && <div className="fine-print" style={{ marginTop: 6 }}>Transaction {a.transactionReference}</div>}
            </div>
          ))}
        </div>
      </section>

      <section className="card" aria-labelledby="observed-heading">
        <div className="row-between">
          <h2 id="observed-heading" style={{ margin: 0 }}>This month so far</h2>
          <span className="badge badge-active">Observed</span>
        </div>
        <p className="text-muted">
          Day {observed.daysElapsed} of {observed.daysInMonth} (UTC month starting {formatIsoDate(observed.monthStart)}). Transfers between your own
          accounts, savings-goal contributions and simulated deposits are not spending.
        </p>
        <div className="kpi" aria-label="Net spent this month">{formatInr(observed.netSpent)}</div>
        <div className="fine-print">
          {formatInr(observed.grossSpent)} paid out across {observed.paymentCount} payment{observed.paymentCount === 1 ? '' : 's'}
          {Number(observed.refundsNetted) > 0 ? `, less ${formatInr(observed.refundsNetted)} in refunds` : ''}
        </div>
        {observed.byCategory.length > 0 && (
          <div className="table-wrap" style={{ marginTop: 12 }}>
            <table>
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Paid out</th>
                </tr>
              </thead>
              <tbody>
                {observed.byCategory.map((c) => (
                  <tr key={c.categoryId}>
                    <td>{c.name}</td>
                    <td>{formatInr(c.amount)}</td>
                  </tr>
                ))}
                {Number(observed.uncategorized) > 0 && (
                  <tr>
                    <td>Uncategorized</td>
                    <td>{formatInr(observed.uncategorized)}</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <section className="card" aria-labelledby="projection-heading">
        <div className="row-between">
          <h2 id="projection-heading" style={{ margin: 0 }}>Projected month-end spending</h2>
          <span className={`badge ${projection.status === 'OK' ? 'badge-warning' : 'badge-closed'}`}>
            {projection.status === 'OK' ? 'Projection (estimate)' : 'Insufficient history'}
          </span>
        </div>
        {projection.status !== 'OK' && (
          <p className="text-muted" style={{ marginTop: 12 }}>
            {projection.reason ?? 'There is not enough spending history yet.'} No projection is shown rather than guessing.
          </p>
        )}
        {projection.status === 'OK' && projection.projectedMonthEnd && projection.basis && (
          <>
            <div className="kpi" style={{ marginTop: 12 }} aria-label="Projected month-end spending">
              {formatInr(projection.projectedMonthEnd)}
            </div>
            <div className="fine-print">
              Estimated range {formatInr(projection.rangeLow ?? projection.projectedMonthEnd)} to {formatInr(projection.rangeHigh ?? projection.projectedMonthEnd)} — the
              spread between two estimation methods, not a statistical confidence interval. Estimates are not guarantees.
            </div>
            <details style={{ marginTop: 12 }}>
              <summary>Assumptions and basis</summary>
              <ul>
                {projection.assumptions.map((a) => (
                  <li key={a}>{a}</li>
                ))}
              </ul>
              <ul className="fine-print">
                <li>History window: {projection.basis.windowDays} days from {formatIsoDate(projection.basis.windowStart)}, {projection.basis.paymentsInWindow} payments</li>
                <li>Typical spending per day: {formatInr(projection.basis.dailyRate)}</li>
                {projection.basis.weeklyMedianDailyRate && <li>Median-week spending per day: {formatInr(projection.basis.weeklyMedianDailyRate)}</li>}
                <li>Time left in the month: {projection.basis.remainingDaysInMonth} days</li>
                {projection.basis.cappedOneOffs && <li>One-off large payments were capped at {formatInr(projection.basis.largestPaymentCap ?? '0')}</li>}
              </ul>
            </details>
          </>
        )}
      </section>

      <section className="card" aria-labelledby="budgets-heading">
        <h2 id="budgets-heading">Budget overrun estimates</h2>
        {data.budgets.length === 0 ? (
          <EmptyState>No budgets set for this month. Add one on the Budgets page to see estimates here.</EmptyState>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Limit</th>
                  <th>Spent so far (observed)</th>
                  <th>Estimate</th>
                </tr>
              </thead>
              <tbody>
                {data.budgets.map((b) => (
                  <BudgetRow key={b.categoryId} budget={b} />
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <section className="card" aria-labelledby="goals-heading">
        <h2 id="goals-heading">Savings goals</h2>
        {data.goals.length === 0 ? (
          <EmptyState>No savings goals yet.</EmptyState>
        ) : (
          <div className="stack">
            {data.goals.map((g) => (
              <GoalCard key={g.goalId} goal={g} />
            ))}
          </div>
        )}
      </section>

      <details className="card">
        <summary>How these are calculated</summary>
        <ul>
          {data.methodology.map((m) => (
            <li key={m}>{m}</li>
          ))}
        </ul>
        <p className="fine-print">Generated {formatDateTime(data.generatedAt)}.</p>
      </details>
    </div>
  )
}

function BudgetRow({ budget }: { budget: InsightsBudgetEstimate }) {
  const status = BUDGET_STATUS[budget.status]
  return (
    <tr>
      <td>{budget.category}</td>
      <td>{formatInr(budget.limit)}</td>
      <td>{formatInr(budget.spent)}</td>
      <td>
        <span className={`badge ${status.className}`}>{status.label}</span>
        {budget.projectedMonthEnd && <div className="fine-print">Projected month-end {formatInr(budget.projectedMonthEnd)}</div>}
        {budget.estimatedOverrun && (
          <div className="fine-print">{budget.status === 'ALREADY_OVER' ? 'Over by' : 'Estimated overrun'} {formatInr(budget.estimatedOverrun)}</div>
        )}
        {budget.reason && <div className="fine-print">{budget.reason}</div>}
      </td>
    </tr>
  )
}

function GoalCard({ goal }: { goal: InsightsGoal }) {
  const percent = Math.min(100, Number(goal.percentComplete))
  const p = goal.projection
  return (
    <div className="card" style={{ marginBottom: 0 }}>
      <div className="row-between">
        <strong>{goal.name}</strong>
        <span className="badge badge-active">Observed</span>
      </div>
      <div className="progress" role="progressbar" aria-label={`${goal.name} progress`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} style={{ margin: '8px 0' }}>
        <span style={{ width: `${percent}%` }} />
      </div>
      <div className="fine-print">
        {formatInr(goal.saved)} saved of {formatInr(goal.target)} ({goal.percentComplete}%) · {formatInr(goal.remaining)} to go
        {goal.targetDate ? ` · target date ${formatIsoDate(goal.targetDate)}` : ''}
      </div>
      {goal.requiredMonthlyForTargetDate && (
        <div className="fine-print">To reach the target by that date you would need about {formatInr(goal.requiredMonthlyForTargetDate)} a month (simple arithmetic, not a forecast).</div>
      )}
      <div style={{ marginTop: 8 }}>
        <span className={`badge ${p.status === 'OK' ? 'badge-warning' : 'badge-closed'}`}>{GOAL_STATUS[p.status]}</span>
        {p.status === 'OK' && p.estimatedCompletionMonth && (
          <div style={{ marginTop: 6 }}>
            At your recent pace of about {formatInr(p.averageMonthlyContribution ?? '0')} a month, this goal could be reached around{' '}
            <strong>{formatMonth(p.estimatedCompletionMonth)}</strong>.
            {p.onPaceForTargetDate === true && ' That is on pace for your target date.'}
            {p.onPaceForTargetDate === false && ' That is behind the pace needed for your target date.'}
            <ul className="fine-print">
              {p.assumptions.map((a) => (
                <li key={a}>{a}</li>
              ))}
            </ul>
          </div>
        )}
        {p.status !== 'OK' && p.status !== 'COMPLETED' && p.reason && <div className="fine-print" style={{ marginTop: 6 }}>{p.reason}</div>}
      </div>
    </div>
  )
}
